home_page = "http://moscow.en.cx/"
username = "berrim0r_en"
password = "anu11927"
phantom_path = "/phantomjs-2.1.1-windows/bin/phantomjs"
my_team_xpath = "/html/body/table[3]/tbody/tr[1]/td/table/tbody/tr/td[1]/div[1]/div/div/table/tbody/tr[6]/td/a"
